config/routes.rb
Freeclicker::Application.routes.draw do

  get '/responses/clear/:question_id', to: "responses#clear"
  get '/responses/count/:question_id', to: "responses#count"
  resources :responses


  resources :answers


  get '/questions/current'
  resources :questions

  root to: "responses#index"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :letter, :question_id, :text

  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :text, :answers_attributes, :active

  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  has_many :responses, dependent: :destroy

  def self.current
    Question.where(active: true).first
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :letter, :question_id, :ip
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    # open or close
    if params[:post] == 'true'
      Question.where(active: true).each do |q|
        q.active = false
      end
      @question.active = true
      @question.save
    elsif params[:post] == 'close'
      @question.active = false
      @question.save
    end

    # get results
    @results = Hash.new(0)
    @question.responses.each do |r|
      @results[r.letter] += 1
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    5.times { answer = @question.answers.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def current
    @question = Question.current

    @question = nil if !@question.nil? && !@question.responses.where(ip: request.remote_ip).first.nil?

    respond_to do |format|
      format.html { render inline: "<%= @question.nil? ? 'No question active.' : @question.text %>"}
      format.json { render json: !@question.nil? }
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  # GET /responses.json
  def index
    @question = Question.current

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responses }
    end
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.create(question_id: params[:question_id], letter: params[:letter], ip: params[:ip])

    respond_to do |format|
      format.html { redirect_to "/", notice: 'Response recorded.' }
    end
  end

  def clear
    Question.find(id: params[:question_id]).responses.to_a.map(&:destroy)

    respond_to do |format|
      format.js { render inline: 'alert("Responses cleared.")'}
    end
  end

  def count
    count = Question.find(params[:question_id]).responses.count

    respond_to do |format|
      format.json { render json: count}
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/answers/_answer_fields.html.erb
<div class="row collapse">
  <div class="small-3 large-2 columns">
    <span class="prefix"><%= ('A'..'Z').to_a[n] %></span>
  </div>
  <div class="small-9 large-10 columns">
    <%= f.text_field :text, placeholder: 'What do you mean? An African or European swallow?' %>
    <%= f.hidden_field :letter, value: ('A'..'Z').to_a[n] %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freeclicker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="large-12 large-centered columns"><%= yield %></div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Question</h4>
  <%= f.text_field :text, placeholder: 'What is the air-speed velocity of an unladen swallow?', required: true %>

  <h4>Answers</h4>

  <% i = 0 %>
  <%= f.fields_for :answers do |builder| %>
    <%= render "answers/answer_fields", f: builder, n: i %>
    <% i += 1 %>
  <% end %>

  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<table>
<% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td><%= link_to 'Open', question_path(question, post: true) %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @question.text %></h1>

<table>
  <% @question.answers.each do |a| %>
    <% unless a.text.blank? %>
      <tr>
        <th style="font-size:20px"><%= a.letter %></th>
        <td style="font-size:20px"><%= a.text %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= link_to 'Open', '?post=true' %> | 
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>
<br>
<br>

<% if @question.active %>
  <h3>This question is open!</h3>
  <%= link_to 'Close', '?post=close', class: 'button' %>
  <span id="num-responses"><%= @question.responses.count %></span>
  <br><br>
<% end %>

<a onclick="$('#results').toggle()">Show Results</a> | <a href='/responses/clear/<%= @question.id %>' data-remote="true">Clear Results</a>

<div id="results" style="display:none">
  <div id="results-chart"></div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  // google chart stuff
  google.load('visualization', '1.0', {'packages':['corechart']});
  google.setOnLoadCallback(drawCharts);

  function drawCharts() {
    var userData = new google.visualization.DataTable();
    userData.addColumn('string', 'Letter');
    userData.addColumn('number', '');
    userData.addRows([
      ['A', <%= @results['A'] %>],
      ['B', <%= @results['B'] %>],
      ['C', <%= @results['C'] %>],
      ['D', <%= @results['D'] %>],
      ['E', <%= @results['E'] %>],
    ]);
    var options = {title:'Results',
                   width:1000,
                   height:300,
                   backgroundColor: 'transparent',
                   legend: {position: 'none'}};
    var chart = new google.visualization.BarChart(document.getElementById('results-chart'));
    chart.draw(userData, options);
  }

  // responses counter
  var count_checker = window.setInterval(function() {
    $.getJSON('/responses/count/<%= @question.id %>.json', function(data) {
      $('#num-responses').html(data)
      console.log(data);
    });
  }, 1000);
</script>

app/views/responses/_ask.html.erb
<h2><%= @question.text %></h2>

<% @question.answers.each do |a| %>
  <% unless a.text.blank? %>
    <div class="row">
      <div class="medium-2 columns">
        <%= button_to a.letter, responses_path(question_id: @question.id, letter: a.letter, ip: request.remote_ip, :method => :post), class: 'small button expand' %>
      </div>
      <div class="medium-10 columns show-for-medium-up">
        <p><%= a.text %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/responses/_wait.html.erb
<h1>FreeClicker</h1>

<p>Please wait for the professor to put up the next question.</p>

<script>
  var checker = window.setInterval(function() {
    $.getJSON('/questions/current.json', function(data) {
      if (data) {
        location.reload();
      }
      console.log(data);
    });
  }, 1000);
</script>

app/views/responses/index.html.erb
<div id="response-area">
  <% if @question.nil? #|| !@question.responses.where(ip: request.remote_ip).first.nil? %>
    <%= render partial: 'wait' %>
  <% else %>
    <%= render partial: 'ask' %>
  <% end %>
</div>